level.min=1
level.max=100

data.listName=player_profile
data.experienceField=experience
data.levelField=level
data.lastNameField=lastName
data.uuidField=uuid
data.comidField=comid
data.updatedAtField=updatedAt

level.requirement.1=100
level.requirement.2=300
level.requirement.3=500
level.requirement.4=1000
level.requirement.5=1500

message.broadcastOnJoin=true
message.joinTemplate=[accent]{name}[] current level [lime]Lv.{level}[] exp [accent]{experience}[]
