# 等级范围
等级.最低等级=1
等级.最高等级=100
等级.经验字段=experience
等级.等级字段=level
等级.是否消耗经验=false

# 经验需求
经验需求.1=100
经验需求.2=300
经验需求.3=500
经验需求.4=1000
经验需求.5=1500

# 进入消息
消息.玩家进入发送=true
消息.进入文本=[accent]{name}[] 当前等级 [lime]Lv.{level}[] 经验 [accent]{experience}[]
消息.允许调用聊天出入插件=true

# 数据
数据.列表名称=player_profile
数据.经验字段=experience
数据.等级字段=level
